language: go
go:
- "1.10"

sudo: required

services:
- docker

env:
- RESYNC_PERIOD=30s

before_install:
- curl -Lo $GOPATH/bin/kubectl https://storage.googleapis.com/kubernetes-release/release/v1.11.4/bin/linux/amd64/kubectl
- curl -Lo $GOPATH/bin/minikube https://storage.googleapis.com/minikube/releases/v0.28.2/minikube-linux-amd64
- curl -Lo $GOPATH/bin/dep https://github.com/golang/dep/releases/download/v0.4.1/dep-linux-amd64
- curl -L https://raw.githubusercontent.com/alecthomas/gometalinter/master/scripts/install.sh | bash -s -- -b $GOPATH/bin
- chmod +x $GOPATH/bin/*
- echo $PATH && ls -la $GOPATH/bin
- sudo -E CHANGE_MINIKUBE_NONE_USER=true $GOPATH/bin/minikube start --vm-driver=none --kubernetes-version=v1.11.4

install: true

before_script:
- git clone --depth=1 https://github.com/kubernetes/kubernetes.git $GOPATH/src/k8s.io/kubernetes

script:
- ./ci/test.sh && ./ci/build.sh && ./ci/package.sh
