apiVersion: stable.shipper/v1
kind: CapacityTarget
metadata:
  name: capacity-v0.0.1 # a SHA1 or git tag from the CI/CD pipeline
  labels:
    release: reviewsapi-4
spec:
  clusters:
    targetPods: 0
  - name: local
