apiVersion: shipper.booking.com/v1
kind: Strategy
metadata:
  name: vanguard
spec:
  steps:
  - name: 5% trial
    capacity:
      incumbentReplicas: 100
      contenderReplicas: 5
    traffic:
      incumbentTraffic: 95
      contenderTraffic: 5
  - name: 50/50
    capacity:
      # incumbentReplicas stays above 50% so we can abort without waiting for incumbent pods to spin up
      incumbentReplicas: 70
      contenderReplicas: 50
    traffic:
      incumbentTraffic: 50
      contenderTraffic: 50
  - name: full on
    capacity:
      incumbentReplicas: 50
      contenderReplicas: 100
    traffic:
      incumbentTraffic: 0
      contenderTraffic: 100
  - name: committed
    capacity:
      incumbentReplicas: 0
      contenderReplicas: 100
    traffic:
      incumbentTraffic: 0
      contenderTraffic: 100
